In [5]:
import pandas as pd
import re
# Leemos el CSV con los códigos por provincia eliminando las 5 primeras columnas que ya
# hemos visto que no son relevantes.
bizkaia = pd.read_csv('Bizkaia.csv', index_col=False,encoding='iso-8859-1',sep=';',skiprows=5)
bizkaia.head(10)

                                          Unnamed: 0    2016
0                   4800101001 Abadiño sección 01001  16.437
1                   4800101002 Abadiño sección 01002  13.468
2                   4800101003 Abadiño sección 01003  11.908
3                   4800101004 Abadiño sección 01004  14.471
4                   4800101005 Abadiño sección 01005  15.348
5  4800201001 Abanto y Ciérvana-Abanto Zierbena s...  12.440
6  4800201002 Abanto y Ciérvana-Abanto Zierbena s...  11.843
7  4800201004 Abanto y Ciérvana-Abanto Zierbena s...  11.482
8  4800201005 Abanto y Ciérvana-Abanto Zierbena s...  12.327
9  4800202001 Abanto y Ciérvana-Abanto Zierbena s...  12.929

In [7]:
# Renombramos las colimnas para ponerles nomnbres normales.
bizkaia.rename(columns={'Unnamed: 0':'identificador','2016':'renta'},inplace=True)
bizkaia

                                 identificador   renta
0             4800101001 Abadiño sección 01001  16.437
1             4800101002 Abadiño sección 01002  13.468
2             4800101003 Abadiño sección 01003  11.908
3             4800101004 Abadiño sección 01004  14.471
4             4800101005 Abadiño sección 01005  15.348
..                                         ...     ...
927          4891301001 Zierbena sección 01001  15.022
928   4891501001 Ziortza-Bolibar sección 01001  15.579
929                                     Notas:     NaN
930                   Estadística experimental     NaN
931  Fuente: Instituto Nacional de Estadística     NaN

[932 rows x 2 columns]

In [8]:
# Nos deshacemos de las últimas filas que tampoco son relevantes.
bizkaia.drop(bizkaia.tail(3).index,inplace=True)
bizkaia

                                identificador   renta
0            4800101001 Abadiño sección 01001  16.437
1            4800101002 Abadiño sección 01002  13.468
2            4800101003 Abadiño sección 01003  11.908
3            4800101004 Abadiño sección 01004  14.471
4            4800101005 Abadiño sección 01005  15.348
..                                        ...     ...
924         4809701002 Zaratamo sección 01002  11.633
925          4802401001 Zeanuri sección 01001  16.040
926          4802501001 Zeberio sección 01001  14.858
927         4891301001 Zierbena sección 01001  15.022
928  4891501001 Ziortza-Bolibar sección 01001  15.579

[929 rows x 2 columns]

In [19]:
# Función para obtener el NIE de la BBDD (base de datos).
def get_NIE (bbdd):
    NIE = []
    for i in range(len(bbdd.identificador)):
        NIE_value = bbdd.identificador[i][0:9]
        NIE.append(NIE_value)
    return NIE
NIE = get_NIE(bizkaia)

AttributeError: 'list' object has no attribute 'dtype'

In [32]:
#Función para obtener la población de la BBDD.

re.findall("[a-zA-Záéíóúñ ]+", bizkaia.identificador[567])[0]
def get_poblacion (bbdd):
    poblacion = []
    for i in range(len(bbdd.identificador)):
        nombre = re.findall("[a-zA-Záéíóúñ\\- ]+", bbdd.identificador[i])[0]
        nombre = re.sub(" sección","",nombre)
        poblacion.append(nombre)
    
    return poblacion

poblacion = get_poblacion(bizkaia)
poblacion

[' Abadiño ',
 ' Abadiño ',
 ' Abadiño ',
 ' Abadiño ',
 ' Abadiño ',
 ' Abanto y Ciérvana-Abanto Zierbena ',
 ' Abanto y Ciérvana-Abanto Zierbena ',
 ' Abanto y Ciérvana-Abanto Zierbena ',
 ' Abanto y Ciérvana-Abanto Zierbena ',
 ' Abanto y Ciérvana-Abanto Zierbena ',
 ' Abanto y Ciérvana-Abanto Zierbena ',
 ' Abanto y Ciérvana-Abanto Zierbena ',
 ' Ajangiz ',
 ' Alonsotegi ',
 ' Alonsotegi ',
 ' Alonsotegi ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amorebieta-Etxano ',
 ' Amoroto ',
 ' Arakaldo ',
 ' Arantzazu ',
 ' Areatza ',
 ' Arrankudiaga ',
 ' Arratzu ',
 ' Arrieta ',
 ' Arrigorriaga ',
 ' Arrigorriaga ',
 ' Arrigorriaga ',
 ' Arrigorriaga ',
 ' Arrigorriaga ',
 ' Arrigorriaga ',
 ' Arrigorriaga ',
 ' Arrigorriaga ',
 ' Artea ',
 ' Artzentales ',
 ' Atxondo ',
 ' Aulesti ',
 ' Bakio ',
 ' Bakio ',
 ' Balmaseda ',
 ' Balmaseda ',
 ' Balmaseda ',
 ' Balmaseda ',
 ' Balmaseda ',
 ' Balmaseda ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barakaldo ',
 ' Barrika ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Basauri ',
 ' Bedia ',
 ' Berango ',
 ' Berango ',
 ' Berango ',
 ' Berango ',
 ' Berango ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Bermeo ',
 ' Berriatua ',
 ' Berriz ',
 ' Berriz ',
 ' Berriz ',
 ' Berriz ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Bilbao ',
 ' Busturia ',
 ' Busturia ',
 ' Derio ',
 ' Derio ',
 ' Derio ',
 ' Derio ',
 ' Dima ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Durango ',
 ' Ea ',
 ' Elantxobe ',
 ' Elorrio ',
 ' Elorrio ',
 ' Elorrio ',
 ' Elorrio ',
 ' Elorrio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Erandio ',
 ' Ereño ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Ermua ',
 ' Errigoiti ',
 ' Etxebarri ',
 ' Etxebarri ',
 ' Etxebarri ',
 ' Etxebarri ',
 ' Etxebarri ',
 ' Etxebarri ',
 ' Etxebarri ',
 ' Etxebarria ',
 ' Forua ',
 ' Fruiz ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdakao ',
 ' Galdames ',
 ' Gamiz-Fika ',
 ' Garai ',
 ' Gatika ',
 ' Gautegiz Arteaga ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Gernika-Lumo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Getxo ',
 ' Gizaburuaga ',
 ' Gordexola ',
 ' Gorliz ',
 ' Gorliz ',
 ' Gorliz ',
 ' G',
 ' G',
 ' G',
 ' G',
 ' G',
 ' Ibarrangelu ',
 ' Igorre ',
 ' Igorre ',
 ' Igorre ',
 ' Ispaster ',
 ' Iurreta ',
 ' Iurreta ',
 ' Iurreta ',
 ' Izurtza ',
 ' Karrantza Harana',
 ' Karrantza Harana',
 ' Kortezubi ',
 ' Lanestosa ',
 ' Larrabetzu ',
 ' Laukiz ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Leioa ',
 ' Lekeitio ',
 ' Lekeitio ',
 ' Lekeitio ',
 ' Lekeitio ',
 ' Lekeitio ',
 ' Lekeitio ',
 ' Lekeitio ',
 ' Lemoa ',
 ' Lemoa ',
 ' Lemoa ',
 ' Lemoiz ',
 ' Lezama ',
 ' Loiu ',
 ' Mallabia ',
 ' Mañaria ',
 ' Markina-Xemein ',
 ' Markina-Xemein ',
 ' Markina-Xemein ',
 ' Maruri-Jatabe ',
 ' Mendata ',
 ' Mendexa ',
 ' Meñaka ',
 ' Morga ',
 ' Mundaka ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Mungia ',
 ' Munitibar-Arbatzegi Gerrikaitz ',
 ' Murueta ',
 ' Muskiz ',
 ' Muskiz ',
 ' Muskiz ',
 ' Muskiz ',
 ' Muskiz ',
 ' Muskiz ',
 ' Muxika ',
 ' Nabarniz ',
 ' Ondarroa ',
 ' Ondarroa ',
 ' Ondarroa ',
 ' Ondarroa ',
 ' Ondarroa ',
 ' Ondarroa ',
 ' Ondarroa ',
 ' Orozko ',
 ' Orozko ',
 ' Ortuella ',
 ' Ortuella ',
 ' Ortuella ',
 ' Ortuella ',
 ' Ortuella ',
 ' Ortuella ',
 ' Otxandio ',
 ' Plentzia ',
 ' Plentzia ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Portugalete ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Santurtzi ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sestao ',
 ' Sondika ',
 ' Sondika ',
 ' Sondika ',
 ' Sopela ',
 ' Sopela ',
 ' Sopela ',
 ' Sopela ',
 ' Sopela ',
 ' Sopela ',
 ' Sopela ',
 ' Sopuerta ',
 ' Sopuerta ',
 ' Sukarrieta ',
 ' Trucios-Turtzioz ',
 ' Ubide ',
 ' Ugao-Miraballes ',
 ' Ugao-Miraballes ',
 ' Ugao-Miraballes ',
 ' Ugao-Miraballes ',
 ' Urduliz ',
 ' Urduliz ',
 ' Urduliz ',
 ' Urduña',
 ' Urduña',
 ' Urduña',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Valle de Trápaga-Trapagaran ',
 ' Zaldibar ',
 ' Zaldibar ',
 ' Zaldibar ',
 ' Zalla ',
 ' Zalla ',
 ' Zalla ',
 ' Zalla ',
 ' Zalla ',
 ' Zamudio ',
 ' Zamudio ',
 ' Zaratamo ',
 ' Zaratamo ',
 ' Zeanuri ',
 ' Zeberio ',
 ' Zierbena ',
 ' Ziortza-Bolibar ']

In [26]:
bizkaia.identificador

0              4800101001 Abadiño sección 01001
1              4800101002 Abadiño sección 01002
2              4800101003 Abadiño sección 01003
3              4800101004 Abadiño sección 01004
4              4800101005 Abadiño sección 01005
                         ...
924           4809701002 Zaratamo sección 01002
925            4802401001 Zeanuri sección 01001
926            4802501001 Zeberio sección 01001
927           4891301001 Zierbena sección 01001
928    4891501001 Ziortza-Bolibar sección 01001
Name: identificador, Length: 929, dtype: object

In [58]:
# Función TOCHA TOCHA
bbdd = ["Álava","Albacete","Alicante","Almeria","Asturias","Avila","Badajoz","Barcelona",
        "Bizkaia","Burgos","Caceres","Cadiz","Catabria","Islas Baleares"]
def get_NIE_poblacion (bbdd):
    #Carga de ficheros CSV
    base =[]
    for i in bbdd:
        datos = pd.read_csv(i+'.csv', index_col=False,encoding='iso-8859-1',sep=';',skiprows=5)
        datos.rename(columns={'Unnamed: 0':'identificador','2016':'renta'},inplace=True)
        datos.drop(bizkaia.tail(3).index,inplace=True)
        base.append(datos)
    NIE = []
    for i in range(len(datos.identificador)):
        NIE_value = int(datos.identificador[i][0:9])
        NIE.append(NIE_value)
    poblacion = []
    for i in range(len(bbdd.identificador)):
        nombre = re.findall("[a-zA-Záéíóúñ\\- /]+", datos.identificador[i])[0]
        nombre = re.sub(" sección","",nombre)
        poblacion.append(nombre)
    d = {'poblacion':poblacion,'NIE':NIE,'renta':base.renta}
    datos = pd.DataFrame(d)
    return datos

basedatos = get_NIE_poblacion(bbdd)

KeyError: '[926 927 928] not found in axis'

In [57]:
bbdd = ["Álava","Albacete","Alicante","Almeria","Asturias","Avila","Badajoz","Barcelona",
        "Bizkaia","Burgos","Caceres","Cadiz","Catabria","Islas Baleares"]
base = []
datos = pd.read_csv(bbdd[0]+'.csv', index_col=False,encoding='iso-8859-1',sep=';',skiprows=5)
datos.rename(columns={'Unnamed: 0':'identificador','2016':'renta'},inplace=True)
datos.drop(datos.tail(3).index,inplace=True)
base.append(datos)
base

[                                     identificador  Renta media por persona   \
 0                                              NaN                    2016.0
 1                        01051 Agurain/Salvatierra                   12374.0
 2          0105101 Agurain/Salvatierra distrito 01                       NaN
 3    0105101001 Agurain/Salvatierra secciÃ³n 01001                       NaN
 4    0105101002 Agurain/Salvatierra secciÃ³n 01002                       NaN
 ..                                             ...                       ...
 364                   0101801 Zigoitia distrito 01                       NaN
 365             0101801001 Zigoitia secciÃ³n 01001                       NaN
 366                                     01063 Zuia                   16474.0
 367                       0106301 Zuia distrito 01                       NaN
 368                 0106301001 Zuia secciÃ³n 01001                       NaN

      Unnamed: 2  Renta media por hogar  Unnamed: 4  Unnamed: 5
 0        2015.0                 2016.0      2015.0         NaN
 1       12083.0                30235.0     29511.0         NaN
 2           NaN                    NaN         NaN         NaN
 3           NaN                    NaN         NaN         NaN
 4           NaN                    NaN         NaN         NaN
 ..          ...                    ...         ...         ...
 364         NaN                    NaN         NaN         NaN
 365         NaN                    NaN         NaN         NaN
 366     16530.0                43594.0     44349.0         NaN
 367         NaN                    NaN         NaN         NaN
 368         NaN                    NaN         NaN         NaN

 [369 rows x 6 columns]]